weights: yolov5s.pt
cfg: models\hub\yolov5-p2.yaml
data: data\mask_data_format.yaml
hyp: data\hyps\hyp.scratch.yaml
epochs: 1
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: true
noval: true
noautoanchor: false
evolve: true
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: true
adam: Ture
sync_bn: false
workers: 0
project: runs\evolve
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\evolve\exp
